### ISSUE TITLE
Certain questions cannot be answered because the cmd key is not override

### ISSUE THREAD

**Issue by amychan331** [Techtonica/keyboard-shortcuts-practice#32] opened 2018-10-05 01:57 UTC
When users answer the "hide the window" question with Cmd-H, it will actually close user's own window, thus the practice would not precede to the next question. The Cmd-h needs to be override somehow.

**Comment by amychan331** [comment] 2018-10-05 02:04
Actually, cmd-h is not the only one. The question on "minimize window" also hides user's own window. (Cmd-M).

**Comment by amychan331** [comment] 2018-10-05 02:07
Actually, make that rest of the question set, because none of the answer that require Cmd works.

**Comment by shiftyp** [comment] 2018-10-09 00:32
I think a solution @amychan331 would be to add `e.preventDefault` to the end of [this `handle` function.](https://github.com/Techtonica/keyboard-shortcuts-practice/blob/master/JS/main.js#L62). This function could use some indentation cleanup as well, maybe a separate issue.

**Comment by amychan331** [comment] 2018-10-09 09:08
@shiftyp Having indentation fix as a separate issue was actually talked about in #35, so I made another pull request for the indentation(#36). For some strange reason, when I merge the changes for indentation, #35 also merged. So I will probably create another pull request later... 
Actually, I did tried the handle function with e.preventDefault(), but it didn't have any effects.

**Comment by shiftyp** [comment] 2018-10-09 14:54
You're right, it's a bit tricker than that. I put together a [JSFiddle](http://jsfiddle.net/shiftyp/2c6yg3r9/) with a solution, which involves preventing the *keyDown* event default when the meta or ctrl keys are engaged. You also need to prevent the *keyPress*. I found this [stackOverflow](https://stackoverflow.com/questions/11000826/ctrls-preventdefault-in-chrome) particularly helpful in putting together a solution.

**Comment by deeptiGarg** [comment] 2018-10-20 20:03
Add next & previous buttons for commands which cannot be overridden.

**Comment by alodahl** [comment] 2020-10-02 15:50
duplicate of #45

**Closed by alodahl** 2020-10-02 15:50 UTC
Labels: Hacktoberfest, bug
