### ISSUE TITLE
Ensure correct user data is being fetched when a user logs in.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#81] opened 2020-09-13 02:14 UTC
Ensure correct user data is being fetched when a user logs in.

**Comment by astha01** [comment] 2020-10-01 17:02
Hi would like to work on it

**Comment by astha01** [comment] 2020-10-01 17:15
Thanks ! @danisyellis

**Comment by vegetabill** [comment] 2020-10-05 23:11
@alodahl this seems like a dupe of #77 to me. Is there some other data that we are expecting to need upon login?

**Comment by alodahl** [comment] 2020-10-07 10:12
I think you're more tuned-in to that at this point...  If you think that's all, please close the issue 🙂

**Comment by vegetabill** [comment] 2020-10-08 04:10
Closing as dupe of #77. If we need more user state upon login, we can open another issue.

**Closed by vegetabill** 2020-10-08 04:10 UTC
Labels: Hacktoberfest, Priority 5, backend, 🛑 blocked
