### ISSUE TITLE
Verify login/logged in button functions (UI)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#79] opened 2020-09-13 02:12 UTC
Now that we have Auth0 integrated in #73 and a simple auth for local development in #74, let's make sure the login/already logged in button shows the correct state. The button should show 'log-in' when there is no user yet, and switch to 'logged in' when the user has been authenticated.

Ensure that the logged in state:

- is visible once the user logs in
- toggles from log-in to logged in in the appropriate states
- feel free to use language or cues other than 'logged in' - we just need to make it clear that their progress is now being saved.

Dependencies:

- Log-in UI with toggle function already exists

**Comment by vegetabill** [comment] 2020-10-06 20:37
@alodahl is this just an accidental dupe of #76 ? I may have created it when triaging issues the day before OSD.

**Comment by alodahl** [comment] 2020-10-07 09:59
It might be, @vegetabill !

**Comment by alodahl** [comment] 2020-10-07 10:08
Unless one is issue is for UI and one is for functionality.

**Comment by vegetabill** [comment] 2020-10-08 04:12
Hmm, I think #75 is the UI part so I'm going to close this as a dupe of #76

**Closed by vegetabill** 2020-10-08 04:12 UTC
Labels: Hacktoberfest, Priority 4, UI, backend, 🛑 blocked
